### ISSUE TITLE
incompatible with arm64 Macs?

### ISSUE THREAD

**Issue by kyleniemeyer** [mathworks/matlab-engine-for-python#13]
I'm trying to install this on my M1 Pro Mac with arm64 architecture. However, it looks like it may only be compatible with the previous CPU architecture.

After installing in a conda environment with Python 3.9 installed, using MATLAB_R2022a, and trying `import matlab.engine`, I get the error:
```
RuntimeError: Could not find directory: /Applications/MATLAB_R2022a.app/extern/engines/python/dist/matlab/engine/maca64
```

I can see that a `maci64` directory is present in `/Applications/MATLAB_R2022a.app/extern/engines/python/dist/matlab/engine/`, however.

**Comment by ugurbolat** [comment]
experiencing the same issue...

**Comment by himoto** [comment]
Same issue.

**Comment by skoldobskiy** [comment]
Now works for R2023b. Probably the issue can be closed.
