### ISSUE TITLE
engine.eval without assigned stdout does not handle Unicode correctly

### ISSUE THREAD

**Issue by allefeld** [mathworks/matlab-engine-for-python#34]
Example: The Unicode character '→' (U+2192) appears in the output as U+001A.

![image](https://github.com/mathworks/matlab-engine-for-python/assets/1738353/ca27c446-e4bf-435c-a2c4-e075857e3697)

That does not happen if the stdout argument is assigned to a `StringIO` instance.

![image](https://github.com/mathworks/matlab-engine-for-python/assets/1738353/bb9a3a4a-b192-4fec-819a-8f2e7a61772e)

However, the disadvantage is that output assigned to stdout is heavily buffered. If I have a long-running computation which continuously produces output, I have to choose between proper Unicode output and immediate feedback.

I though this might be a property of `StringIO`, and tried to intercept `write` calls.

![image](https://github.com/mathworks/matlab-engine-for-python/assets/1738353/a1e5878c-6928-4aba-8d89-611193032b7f)

But from the result it is clear that `stdout.write` is only called once. I also tried to induce flushing by inserting newline characters in the output, with no success.

**Comment by allefeld** [comment]
Just tested with R2023b and matlabengine 23.2.1, and the bug remains.

@alanfmw, not sure whether these issues are actually monitored?

**Comment by alanfmw** [comment]
@allefeld, we will look into this.

**Comment by allefeld** [comment]
Are there any news on this?

**Comment by alanfmw** [comment]
R2024a contains a fix. On Linux and Mac, with UTF-8 display, you will now see the Unicode character displayed correctly. On Windows, it depends on the machine locale. On a Chinese machine, we saw the Unicode output written to the Windows console correctly, but on a US machine, the Unicode output to the Windows console was swallowed, and changing the code page with `chcp` didn't help. Which platform are you using?

**Comment by allefeld** [comment]
Great, I'll check it out!

I'm on Linux, Debian 12.5.

__Edit:__ Can confirm it is fixed with R2024a on Linux.
