### ISSUE TITLE
Add dictionary methods for the workspace

### ISSUE THREAD

**Issue by rsp34** [mathworks/matlab-engine-for-python#42]
Sometimes I'd like to check what is in my workspace. Could the `keys` method be implemented for the workspace?

**Comment by alanfmw** [comment]
You can use the MATLAB `who` method to retrieve the names of the variables in the workspace. For instance:
```

import matlab.engine
eng = matlab.engine.start_matlab('-desktop')
...
vars = eng.who()
vars
['a', 'b']
```

**Comment by rsp34** [comment]
@alanfmw, thanks for the resolution. I was in _Python_ mode.
