### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by WarsawAtDeere** [mathworks/matlab-engine-for-python#9]
I am trying to update matlab python engine for python 3.10. I am using matlab r2019b and unfortunately cannot upgrade to a newer version. I have edited all of the instances of `_supported_versions` to include `'3.10` or `3_10` and when I run setup.py It looks like it builds correctly but it still fails to import "matlabengineforpython3_10". Is there a way to generate/compile that file by my self or do I need to wait for Mathworks to add support for python 3.10?

**Comment by lukasmu** [comment]
@WarsawAtDeere did you manage to solve this issue?
